language: java
jdk:
- oraclejdk8
env:
  matrix:
  - TESTS=OGC_TESTS
  - TESTS=API
  global:
  - SSH_KEY="id_rsa"
  - GIT_NAME="Isabel Rios"
  - GIT_EMAIL="isabelrios@gmail.com"
  - SOURCE_DIR="/home/travis/build/mozilla-sensorweb/sensorthings/test/TE_BASE/users/travis/s0001/html/sta10-0.8-SNAPSHOT.html"
  - DEPLOY_BRANCH="master"
matrix:
  allow_failures:
  - env: TESTS=OGC_TESTS
before_install:
- openssl aes-256-cbc -K $encrypted_d01e2d6e9c35_key -iv $encrypted_d01e2d6e9c35_iv
  -in id_rsa.enc -out id_rsa -d
- openssl aes-256-cbc -K $encrypted_cbecbf2e8b54_key -iv $encrypted_cbecbf2e8b54_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- java -version
- wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
- source ~/.nvm/nvm.sh
- nvm install 6.9.1
- npm install
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- if [[ "$TESTS" = "API" ]]; then npm run test; fi
- if [[ "$TESTS" = "OGC_TESTS" ]]; then npm run example & fi
script:
- if [[ "$TESTS" = "OGC_TESTS" ]]; then source ./scripts/OGC_tests/install_tests.sh ; fi
- if [[ "$TESTS" = "OGC_TESTS" ]]; then source ./scripts/preconditions.sh ; fi
- if [[ "$TESTS" = "OGC_TESTS" ]]; then source ./scripts/OGC_tests/launch_tests.sh ; fi
after_script:
- if [[ "$TESTS" = "OGC_TESTS" ]]; then npm run gh-pages-travis; fi
after_success:
- if [[ "$TESTS" = "API" ]]; then npm run coverage ; fi
